name: 'DEV Shipa Action'
description: 'Creates Shipa application'
inputs:
  shipa-action:
    description: 'File path to consolidated Shipa action yml file'
    required: true
runs:
  using: 'docker'
  image: 'docker://vmanilo/shipa-action:0.1.9'
  args:
    - --shipa-action=${{ inputs.shipa-action }}
    - --debug
